Climber
SaintsRobotics/Crescendo2024 pull request #12
Opened 2024-02-21 00:53 UTC by ProgrammingSR

2024-02-21 22:53 UTC, ReeledWarrior14 requested changes, later dismissed
This does not look like it will work. I think we will need to wait until it can be tested before merging it. There are a lot of issues that need to be fixed. Also please update the branch before saying it is ready for a review, half the changes make no sense since it is not up to date with main.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on build.gradle
> -    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
What is this?

2024-02-21 22:53 UTC, ReeledWarrior14 commented on simgui-ds.json
> +{
Remove all of these changes, or see what the difference is after merging main into this branch properly.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/Constants.java
> +        public static final double kFrontLeftTurningEncoderOffset = 0;
These were removed in main, they should not be here.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/Constants.java
> +        public static final double kPModuleTurningController = -0.3;
Again, a change made in main, not updated/being redone in this branch.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/Constants.java
> +    public static class IntakeConstants {
Intake and shooter changes should not be on this branch.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/RobotContainer.java
> +  private final XboxController m_operatorController = new XboxController(IOConstants.kDriverControllerPort);
Operator controller should not be initialized with the driver controller port. This is a major bug.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
Unused import, please remove.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +        // SmartDashboard.putNumber("Pressure", m_compressor.getPressure());
These should not be commented out or they should be removed.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +    //TODO:fix doc
This is just... its literally a one line java doc, it takes more effort to write the TODO to fix it than to actually just fix it if there is something wrong with it.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +    public void toggle() {
Formatting is wrong here and none of the Javadocs are done properly.

2024-02-21 22:53 UTC, ReeledWarrior14 commented on src/main/java/frc/robot/subsystems/ClimberSubsystem.java
> +        m_leftSolenoid.set(kOff);
Literally all of these methods with different names set the solenoids to kOff. This is another major bug that really should never even have been committed.

2024-02-24 02:52 UTC, dpk2442 approved these changes

2024-02-24 02:55 UTC, merged